no_comment_extensions = [
    '.exe', '.dll', '.so', '.dylib', '.bin', '.msi', '.bat', '.com', '.cmd',
    '.jar', '.war', '.ear', '.pyc', '.pyd', '.lib', '.a', '.lo', '.la',
    '.sys', '.drv', '.efi', '.app', '.apk', '.deb', '.rpm', '.pkg', '.vxd',
    '.cpl', '.ocx', '.scr', '.cda', '.cue', '.nrg', '.mdf', '.vmdk', '.iso',
    '.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff', '.svg', '.webp', '.ico',
    '.raw', '.psd', '.ai', '.eps', '.indd', '.heic', '.jfif', '.jfxx', '.jfi',
    '.cr2', '.nef', '.arw', '.orf', '.sr2', '.dng', '.ppm', '.pgm', '.pbm',
    '.pnm', '.dds', '.tga', '.exr', '.hdr', '.dib', '.pfm', '.mp3', '.wav',
    '.aac', '.flac', '.ogg', '.wma', '.m4a', '.aiff', '.alac', '.amr', '.mid',
    '.midi', '.ra', '.opus', '.pcm', '.wpl', '.dts', '.mka', '.m3u', '.pls',
    '.wv', '.oga', '.spx', '.sln', '.tta', '.ac3', '.eac3', '.m4p', '.m4b',
    '.m4r', '.mpc', '.ape', '.vqf', '.mp4', '.avi', '.mkv', '.mov', '.wmv',
    '.flv', '.webm', '.mpeg', '.mpg', '.m4v', '.3gp', '.3g2', '.mts',
    '.m2ts', '.ts', '.vob', '.rmvb', '.ogv', '.divx', '.xvid', '.rm', '.swf',
    '.f4v', '.mxf', '.roq', '.nsv', '.asf', '.drc', '.mng', '.tp', '.trp',
    '.svi', '.viv', '.qt', '.m2v', '.f4p', '.f4a', '.f4b', '.csv', '.json',
    '.xml', '.yaml', '.yml', '.ini', '.toml', '.cfg', '.dat', '.db',
    '.sqlite', '.sqlite3', '.mdb', '.accdb', '.dbf', '.log', '.tsv', '.sav',
    '.bak', '.dmp', '.blob', '.cdb', '.gdb', '.ndb', '.sql', '.psql', '.db2',
    '.fdb', '.ldb', '.ndf', '.sdf', '.sqlitedb', '.sqlitebackup', '.zip',
    '.rar', '.tar', '.gz', '.7z', '.bz2', '.xz', '.tgz', '.tar.gz',
    '.tar.bz2', '.tar.xz', '.dmg', '.cab', '.arj', '.ace', '.z', '.lz',
    '.lzh', '.sit', '.sitx', '.txz', '.tz', '.s7z', '.lzma', '.snappy',
    '.gzip', '.uue', '.cbr', '.cbz', '.zstd', '.zst', '.map'
]